services:
  - name: tianji-web
    type: web
    env: docker
    branch: main
    plan: starter
    region: oregon        # choose your region
    repo: https://github.com/msgbyte/tianji
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOW_REGISTER
        value: "false"     # disable open registration
      # Add database settings, JWT secret, etc
      - key: DATABASE_URL
        fromDatabase:
          name: tianji-db
          property: connectionString
    # you can add buildCommand/preDeploy/startCommand if needed

databases:
  - name: tianji-db
    engine: postgresql
    plan: starter      # change as needed
    region: oregon
