services:
  - name: tianji-web
    type: web
    env: docker
    branch: main
    repo: https://github.com/msgbyte/tianji
    dockerfilePath: Dockerfile
    autoDeploy: true
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tianji-db  # MUST match the name of the DB you create in Render dashboard
          property: connectionString
      - key: ALLOW_REGISTER
        value: "false"
      - key: JWT_SECRET
        generateValue: true
