services:
  - name: tianji-web
    type: web
    env: docker
    branch: main
    repo: https://github.com/msgbyte/tianji
    dockerfilePath: Dockerfile
    autoDeploy: true
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          name: tianji-db
          type: postgres
          property: connectionString
      - key: ALLOW_REGISTER
        value: "false"  # Or "true" if you want public registration
      - key: JWT_SECRET
        generateValue: true  # Or set your own

  - name: tianji-db
    type: postgres
    plan: starter
    region: oregon
